
<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">
    <?php echo (isset($this->alert) ? $this->alert:''); ?>

    <form action ="<?php echo BASE; ?>encgeral/registrar" enctype="multipart/form-data" class="form-horizontal" method = "post">

    <div class="col-sm-12">
          <h3>Eventos de encerramento de todos os projeto.</h3>
           <legend></legend>
           <h4 class="alert alert-info">
            Nesta tela é possível criar e/ou atualizar relatório de Eventos de encerramento de todos os projeto. <br>
            1. Selecionar o nome da instituição, <br>
            2. Preencher o formulário e <br>
            3. Clicar em Enviar. <br>
            Verifique a situação da instituição na aba Relatórios. <br>
            Apenas instituições com situação em aberto são listadas abaixo.
        </h4>
        </div>
 
        <div class="form-group">
          <label for="nome" class="col-sm-3 control-label">Nome da Instituição:</label>
          <div class="col-sm-8">
              <select class="form-control" name = "name_institution" id="name_institution">
                  <?php 
                    foreach ($view_institutions as $institution) :
                      if (!$institution->situation) : ?>
                  ?>
                    <option>
                       CNPJ>> <?php echo $institution->cnpj; ?> >>
                      <?php echo $institution->name_institution; ?>                        
                    </option>
                  <?php 
                      endif;
                    endforeach;
                  ?>    
              </select>
           </div>
        </div>
         
        <div class="form-group">
            <label for="imagem" class="col-sm-3 control-label">Data</label>
            <div class="col-sm-8">
               <input required class="form-control" type="date" name="evt_enc_geral_data" id="evt_enc_geral_data">
            </div>
        </div>

        <div class="form-group">
            <label for="imagem" class="col-sm-3 control-label">Participação da Comunidade</label>
            <input type="radio" name="participacao_com" id="participacao_com" value="1" checked >Sim
            <input type="radio" name="participacao_com" id="participacao_com" value="0">Não                    
        </div>

            <div class="form-group">
                <label for="imagem" class="col-sm-3 control-label">Evidências 1</label>
                <input type="file" name="evt_enc_geral_img_1" >
            </div>

            <div class="form-group">
                <label for="imagem" class="col-sm-3 control-label">Evidências 2</label>
                <input type="file" name="evt_enc_geral_img_2" >
            </div>

            <div class="form-group">
                <label for="imagem" class="col-sm-3 control-label">Evidências 3</label>
                <input type="file" name="evt_enc_geral_img_3" >
            </div>


        <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
            <input type="submit" class="btn btn-success">
            <input type="reset" class="btn btn-success" value="Limpar">
            <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
        </div>
      </div>
    </form>
</div>
