<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">
    <?php echo (isset($this->alert) ? $this->alert:''); ?>

    <form action ="<?php echo BASE; ?>questionario/registrar" class="form-horizontal" method = "post">
     <h3>Questionário Qualitativo</h3>
     <legend> </legend>
        
      <div class="col-sm-12">
        <label for="exampleTextarea" class="col-sm-4 control-label">a)  Quais dificuldades encontradas na regularização jurídica das instituições?</label>
        <div class="col-sm-8">
          <textarea class="form-control" name= "questao_1" id="questao_1" rows="3"></textarea> <br>   
      </div>
      </div>

      <div class="col-sm-12">
        <label for="exampleTextarea" class="col-sm-4 control-label">b)  Quais dificuldades encontradas nos eventos para a definição dos projetos individuais?</label>
        <div class="col-sm-8">
          <textarea class="form-control" name= "questao_2" id="questao_2" rows="3"></textarea> <br>  
        </div>   
      </div> 

      <div class="col-sm-12">
        <label for="exampleTextarea" class="col-sm-4 control-label">c)  Quais as dificuldades encontradas para a elaboração de projetos?</label>
        <div class="col-sm-8">
          <textarea class="form-control" name= "questao_3" id="questao_3" rows="3"></textarea> <br>
        </div>   
      </div> 

      <div class="col-sm-12">
         <label for="exampleTextarea" class="col-sm-4 control-label">d)  Quais as dificuldades encontradas na execução dos projetos?</label>
        <div class="col-sm-8">
         <textarea class="form-control" name= "questao_4"  id="questao_4" rows="3"></textarea>   <br>
        </div>   
      </div>

       <div class="col-sm-12">
          <label for="exampleTextarea" class="col-sm-4 control-label">e)  Escreva como as instituições e a ADEMADAN executam o projeto de comunicação.</label>
        <div class="col-sm-8">
         <textarea class="form-control" name= "questao_5" id="questao_5" rows="3"></textarea>   <br>
        </div>   
      </div> 

      <div class="col-sm-12">
        <label for="exampleTextarea" class="col-sm-4 control-label">f) Escreva sobre a expectativa e envolvimento das comunidades em seus projetos.</label>
        <div class="col-sm-8">
         <textarea class="form-control" name= "questao_6" id="questao_6" rows="3"></textarea>    <br>
        </div>   
      </div> 

      <div class="col-sm-12">
        <label for="exampleTextarea" class="col-sm-4 control-label">g)  Escreva sobre o que considera relevante para a análise da gestão dos projetos. </label>
        <div class="col-sm-8">
         <textarea class="form-control" name= "questao_7" id="questao_7" rows="3"></textarea>  <br>
        </div>   
      </div> 

      <div class="form-group">
      <div class="col-sm-offset-4 col-sm-12">
        <input type="submit" class="btn btn-success">
        <input type="reset" class="btn btn-success" value="Limpar">
        <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
      </div>
    </div>
  </form>
</div>
