
<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">
    <?php echo (isset($this->alert) ? $this->alert:''); ?>

    <form action ="<?php echo BASE; ?>apresentacao/registrar" enctype="multipart/form-data" class="form-horizontal" method = "post">
      <div class="col-sm-12">
        <h3>Audiências para apresentação de projeto.</h3>
        <legend></legend>
        <h4 class="alert alert-info">
        Nesta tela é possível criar novo relatório de Audiências para apresentação de projeto. <br>
        Basta selecionar o nome da instituição na lista abaixo, <br> preencher o formulário e então clicar em Enviar. <br>
        Verifique a situação da instituição na aba Relatórios. <br>
        Apenas instituições com situação em aberto são listadas abaixo.

    </h4>
      </div>

       <div class="form-group">
        <label for="nome" class="col-sm-3 control-label">Instituição:</label>
        <div class="col-sm-8">
          <select required class="form-control" name = "name_institution" id="name_institution">
                <?php 
                  foreach ($view_institutions as $institution) :
                    if (!$institution->situation) : ?>
                ?>
                  <option>
                     CNPJ>> <?php echo $institution->cnpj; ?> >>
                    <?php echo $institution->name_institution; ?>                        
                  </option>
                <?php 
                    endif;
                  endforeach;
                ?>
            </select>
          </div>
      </div>  

      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Data</label>
          <div class="col-sm-8">
              <input required type="date" name="data" class="form-control" id="data">
          </div>
      </div>

      <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label">Ata</label>
          <input required type="file" name="ata" id="ata" >
        </div>

         <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label"> Evidência 1</label>
          <input type="file" name="img_1" id="img_1" >
        </div>

      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Evidência 2</label>
          <input type="file" name="img_2" id="img_2">
      </div>
      
      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Evidência 3</label>
          <input type="file" name="img_3" id="img_3">
      </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <input type="submit" class="btn btn-success">
                <input type="reset" class="btn btn-success" value="Limpar">
                <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
            </div>
        </div>
    </form>
</div>
