<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>topo_modulo_administrativo_ambiental_novo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
                <div class = "alert alert-block alert-warning">
                    <h4>
                    Recuperação de senha
                    </h4>
                    Será encaminhado um link de redefinição de senha para e-mail cadastrado!
                </div>
                <form class="form-horizontal">
                   
                    <div class="form-group">
                        <label for="username" class="col-sm-3 control-label">Nome usuário:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="inputEmail3" placeholder="Nome de usuário">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-6">
                            <button type="submit" class="btn btn-success">Enviar link de nova senha</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>