<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>

<div class="panel-body">
    <?php 
      echo (isset($this->alert) ? $this->alert : '');
    ?>

  	<div class="table-responsive">
		<h3>Informações Gerais </h3>
    	<table class="table">
            <tr>
            	<th>Instituição:</th>
                <td>
                	<?php echo $view_report->nome_instituicao;?>
                </td>
                <td></td>
                <td></td>
            </tr>
           <tr>
            	<th>CNPJ:</th>
                <td>
                	<?php  echo $view_report->cnpj;?>
                </td>
                <td></td>
                <td></td>
            </tr>
            <tr>
            	<th>Aplicação:</th>
                <td>
                	<?php echo $view_report->aplicacao;?>
                </td>
               
			 	
            </tr>
    	</table>
    </div>

     <div class="table-responsive">
	<h3>Relatório de Diagnóstico </h3>
    	<table class="table">
	    	<thead>
				<tr>
					<th>Status</th>
					<th>Relatório</th>
				</tr>
			</thead>
			<tbody>
			 	<tr>					
					<td>					
				 		<?php if($view_report->apl_validacao === 1) : ?>
								Sim
							<?php else : ?>
								Não
						<?php endif;?>				
					</td>
					<td>					
						<?php if(!is_null($view_report->rel_diag)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->rel_diag;?>" style="color: #0071BF" >Relatório de diagnóstico</a><br>
						<?php endif; ?>
					</td>
				</tr>
			</tbody>
     	</table>
     </div>

 	<div class="table-responsive">
		<h3>Regularização jurídica </h3>
    	<table class="table">
	    	<thead>
				<tr>
					<th>Ata da Diretoria</th>
					<th>Estatuto</th>
				</tr>
			</thead>
			<tbody>
			 	<tr>
					<td>
					<?php if(!is_null($view_juridico)) : ?>
						<?php if(!is_null($view_juridico->ata)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_juridico->cnpj.'/'.$view_juridico->ata;?>" style="color: #0071BF" >Ata</a><br>
						<?php endif; ?>
					</td>
					<td>
						<?php if(!is_null($view_juridico->estatuto)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_juridico->cnpj.'/'.$view_juridico->estatuto;?>" style="color: #0071BF" >Estatuto</a><br>
						<?php endif; ?>
					<?php endif; ?>
					</td>
				</tr>
			</tbody>
     	</table>
     </div>

<div class="table-responsive">
		<h3>Monitoramento</h3>
    	<table class="table">
    		<thead>
				<tr>
					<th>Tipo de evento</th>
					<th>Data</th>
					<th>Arquivos</th>
				</tr>
			</thead>
			<tbody>
				<tr>
				<td>Apresentação 1	</td>

					<td><?php echo date( 'd/m/Y', strtotime($view_report->data_apr_1));?></td>
					<td>
						<?php if(!is_null($view_report->ata_apr_1)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->ata_apr_1;?>" style="color: #0071BF" >Ata</a> <br>
						<?php endif; ?>

						<?php if(!is_null($view_report->img_apr_1)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->img_apr_1;?>" style="color: #0071BF" >Evidência</a><br>
						<?php endif; ?>
					</td>
				</tr>
				<tr>
				<td>Apresentação 2</td>
					<td><?php echo date( 'd/m/Y', strtotime($view_report->data_apr_2));?></td>
					<td>
						<?php if(!is_null($view_report->ata_apr_2)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->ata_apr_2;?>" style="color: #0071BF" >Ata</a> <br>
						<?php endif; ?>

						<?php if(!is_null($view_report->img_apr_2)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->img_apr_2;?>" style="color: #0071BF" >Evidência</a><br>
						<?php endif; ?>
					</td>
				</tr>
				<td>Apresentação 3</td>
					<td><?php echo date( 'd/m/Y', strtotime($view_report->data_apr_3));?></td>
					<td>
						<?php if(!is_null($view_report->ata_apr_3)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->ata_apr_3;?>" style="color: #0071BF" >Ata</a> <br>
						<?php endif; ?>

						<?php if(!is_null($view_report->img_apr_3)) : ?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->img_apr_3;?>" style="color: #0071BF" >Evidência</a><br>
						<?php endif; ?>
					</td>
				</tr>
			</tbody>
    	</table>
    </div> 

    <div class="table-responsive">
	<h3>Oficinas de Elaboração de Projetos. </h3>
    	<table class="table">
	    	<thead>
				<tr>
					<th>Data da Oficina</th>
					<th>Arquivos</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($view_oficina as $evt) : ?>
			 	<tr>	
					<td>
						<?php echo date( 'd/m/Y', strtotime($evt->data)); ?> <br>
					</td>
					<td>
						<?php if(!is_null($evt->ata)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->ata;?>" style="color: #0071BF" >Ata<br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_1)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_1;?>" style="color: #0071BF" >Evidência 1</a><br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_2)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_2;?>" style="color: #0071BF" >Evidência 2</a><br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_3)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_3;?>" style="color: #0071BF" >Evidência 3</a>
						<?php endif; ?>					
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
     	</table>
     </div>

       	<div class="table-responsive">
		<h3>Audiências para Definição de Projeto.</h3>
    	<table class="table">
	    	<thead>
				<tr>
					<th>Data da Audiencia</th>
					<th>Arquivos</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($view_definicao as $evt) : ?>
			 	<tr>	
					<td>
						<?php echo date( 'd/m/Y', strtotime($evt->data)); ?> <br>
					</td>
					<td>
						<?php if(!is_null($evt->ata)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->ata;?>" style="color: #0071BF" >Ata<br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_1)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_1;?>" style="color: #0071BF" >Evidência 1</a><br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_2)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_2;?>" style="color: #0071BF" >Evidência 2</a><br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_3)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_3;?>" style="color: #0071BF" >Evidência 3</a>
						<?php endif; ?>					
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
     	</table>
     </div>

    <div class="table-responsive">
	<h3>Audiências para Apresentação de Projeto.</h3>
    	<table class="table">
	    	<thead>
				<tr>
					<th>Data da Audiencia</th>
					<th>Arquivos</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($view_apresentacao as $evt) : ?>
			 	<tr>	
					<td>
						<?php echo date( 'd/m/Y', strtotime($evt->data)); ?> <br>
					</td>
					<td>
						<?php if(!is_null($evt->ata)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->ata;?>" style="color: #0071BF" >Ata<br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_1)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_1;?>" style="color: #0071BF" >Evidência 1</a><br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_2)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_2;?>" style="color: #0071BF" >Evidência 2</a><br>
						<?php endif; ?>

						<?php if(!is_null($evt->img_3)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_3;?>" style="color: #0071BF" >Evidência 3</a>
						<?php endif; ?>					
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
     	</table>
     </div>

	<div class="table-responsive">
		<h3>Projetos por Instituição </h3>
    	<table class="table">
	    	<thead>
				<tr>
					<th>Titulo</th>
					<th>Objetivo</th>
					<th>Dificuldades</th>
					<th>Site</th>
					<th>Arquivos</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($view_projetos as $evt) : ?>
			 	<tr>
					<td>
						<?php echo $evt->titulo; ?> 
					</td>
					<td>	
						<?php echo $evt->objetivo; ?>
					</td>
					<td> 
						<?php echo $evt->questao; ?>
					</td>
					<td> 
						<?php echo $evt->site_projeto; ?>
					</td>
					
					<td>
						<?php if(!is_null($evt->arquivo)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->arquivo;?>" style="color: #0071BF" >Projeto<br></a>
						<?php endif; ?>			
					
						<?php if(!is_null($evt->banner_projeto)) :	?>
							<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->banner_projeto;?>" style="color: #0071BF" >Banner<br></a>
						<?php endif; ?>			
					
						<?php if(!is_null($evt->video_projeto)) :	?>
							<a href="<?php echo BASE.'visualizar/video/'.$evt->cnpj.'/'.$evt->video_projeto;?>" style="color: #0071BF" >Vídeo<br></a>
						<?php endif; ?>		
					</td>	
				</tr>
				<?php endforeach; ?>	
			</tbody>
     	</table>
     </div>

     <div class="table-responsive">
		<h3>Cronograma físico-financeiro</h3>
    	<table class="table">
    	<thead>
			<tr>
				<th>Ação</th>
				<th>Valor de Desembolso (R$)</th>
				<th>Data de desembolso</th>
				<th>Arquivos</th>				
			</tr>
		</thead>
		<tbody>
			<?php foreach($view_financeiro as $evt) : ?>
		 	<tr>
				<td>
					<?php echo $evt->acao; ?>
				</td>
				<td> 
					R$ <?php echo $evt->desembolso_valor; ?> 
				</td>
				<td>	
					<?php echo date( 'd/m/Y', strtotime($evt->desembolso_data)); ?>
				</td>
				<td>
					<?php if(!is_null($evt->rel_financeiro)) :	?>
						<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->rel_financeiro;?>" style="color: #0071BF" >Evidência<br>
					<?php endif; ?>			
				</td>
			</tr>
			<?php endforeach; ?>	
		</tbody>
     	</table>
     </div>

	<div class="table-responsive">
		<h3>Evento de Encerramento por projeto</h3>
    	<table class="table">
    	<thead>
			<tr>
				<th>Título</th>
				<th>Data</th>
				<th>Arquivos</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($view_encerramento as $evt) : ?>
		 	<tr>
				<td>
					<?php echo $evt->projeto; ?>
				</td>
				<td>	
					<?php echo date( 'd/m/Y', strtotime($evt->data)); ?>
				</td>
				<td>
					<?php if(!is_null($evt->img_1)) :	?>
						<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_1;?>" style="color: #0071BF" >Evidência 1</a><br>
					<?php endif; ?>

					<?php if(!is_null($evt->img_2)) :	?>
						<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_2;?>" style="color: #0071BF" >Evidência 2</a><br>
					<?php endif; ?>

					<?php if(!is_null($evt->img_3)) :	?>
						<a href="<?php echo BASE.'visualizar/baixar/'.$evt->cnpj.'/'.$evt->img_3;?>" style="color: #0071BF" >Evidência 3</a>
					<?php endif; ?>			
					</td>	
			</tr>
			<?php endforeach; ?>	
		</tbody>
     	</table>
     </div>

	<div class="table-responsive">
		<h3>Pessoas contempladas pelos projetos</h3>
    	<table class="table">
    	<thead>
			<tr>
				<th>Título</th>
				<th>Pessoas Atingidas Diretamente</th>
				<th>Pessoas Atingidas Indiretamente</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($view_projetos as $evt) : ?>
		 	<tr>
				<td>
					<?php echo $evt->titulo; ?>
				</td>
				<td>	
					<?php echo $evt->p_contempladas_diretamente; ?>
				</td>
				<td>	
					<?php echo $evt->p_contempladas_indiretamente; ?>
				</td>	
			</tr>
			<?php endforeach; ?>	
		</tbody>
     	</table>
     </div>

     <div class="table-responsive">
		<h3>Evento de Encerramento de Todos os Projetos</h3>
    	<table class="table">
    	<thead>
			<tr>
				<th>Data do evento</th>
				<th>Participação da Comunidade</th>
				<th>Arquivos</th>
			</tr>
		</thead>
		<tbody>
	 	<tr>
			<td>
				<?php echo date( 'd/m/Y', strtotime($view_report->evt_enc_geral_data)); ?>
			</td>
			<td>	
				<?php if($view_report->participacao_com === 1) : ?>
						Sim
					<?php else : ?>
						Não
				<?php endif;?>
			</td>
			<td>
				<?php if(!is_null($view_report->evt_enc_geral_img_1)) :	?>
					<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->evt_enc_geral_img_1;?>" style="color: #0071BF" >Evidência 1</a><br>
				<?php endif; ?>

				<?php if(!is_null($view_report->evt_enc_geral_img_2)) :	?>
					<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->evt_enc_geral_img_2;?>" style="color: #0071BF" >Evidência 2</a><br>
				<?php endif; ?>

				<?php if(!is_null($view_report->evt_enc_geral_img_3)) :	?>
					<a href="<?php echo BASE.'visualizar/baixar/'.$view_report->cnpj.'/'.$view_report->evt_enc_geral_img_3;?>" style="color: #0071BF" >Evidência 3</a>
				<?php endif; ?>			
			</td>	
		</tr>
		</tbody>
     	</table>
     </div>
</div>