<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>

<div class="panel-body">
    <?php 
      echo (isset($this->alert) ? $this->alert : '');
    ?>
    <table class="table">
		<thead>
			<tr>
				<th>Instituição</th>
				<th>Visualizar</th>
				<th>Estatus</th>
				<th>Situação</th>
			</tr>
		</thead>
		<tbody>
		<?php 
			if ($view_reports) : 
			foreach ($view_reports as $report) : 
		?>
		<tr>
			<td><?php echo $report->name_institution; ?></td>
			<td><a href="<?php echo BASE . 'visualizar/geralrelatorio/' . $report->cnpj; ?>" class="btn btn-xs btn-info">
						<i class="fa"></i> Visualizar</a>
			</td>

			<td>
			<?php if ($report->status === 0) : ?>
			    <h4 class=" alert-warning">
			        Reprovado
			    </h4>					
			<?php else: ?>
		 	   	<h4 class=" alert-success">
			        Aprovado
			    </h4>				
			<?php endif; ?>
			</td>
					<td>
			<?php if ($report->situation === 0) : ?>
			    <h4 class=" alert-success">
			        Aberto
			    </h4>					
			<?php else: ?>
		 	   	<h4 class=" alert-danger">
			        Fechado
			    </h4>				
			<?php endif; ?>
			</td>
		</tr>
		<?php 
			endforeach;
			endif;
		?>
		</tbody>
	</table>

	<table class="table">
		<thead>
			<tr>
				<th>Instituição</th>
				<th>Visualizar</th>
			</tr>
		</thead>
		<tbody>
			<?php 
				if ($view_ademadanreport) : 
				foreach ($view_ademadanreport as $report) : 
			?>
			<tr>
				<td>ADEMADAN</td>

				<td><a href="<?php echo BASE . 'visualizar/ademadanrelatorio/' . $report->user_id; ?>" class="btn btn-xs btn-info">
							<i class="fa"></i> Visualizar
						</a></td>
			</tr>
			<?php 
				endforeach;
				endif;
			?>
		</tbody>
	</table>

</div>