
<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">
    <?php echo (isset($this->alert) ? $this->alert:''); ?>

    <div class="col-sm-12">
      <h3>Projetos por Instituição.</h3>
      <legend></legend>
              <h4 class="alert alert-info">
            Nesta tela é possível criar e/ou atualizar relatório de Projetos. <br>
            Para criar novo relatório basta clicar em Novo.<br>
            Para atualizar um relatório:<br>
            1. Selecionar o nome da instituição, <br>
            2. Clicar em Pesquisar, <br> 
            3. Selecionar qual relatório deseja atualizar, <br>
            4. Preencher o formulário e <br>
            5. Clicar em Enviar. <br>
            Verifique a situação da instituição na aba Relatórios. <br>
            Apenas instituições com situação em aberto são listadas abaixo.
        </h4>
    </div>
     <div class="form-group">
            <div  class="col-sm-offset-0 col-sm-10">
                <a href="<?php echo BASE . 'projetos/cadastrar'; ?>" class="btn btn-success" > Novo   </a>  
            </div>
        </div> 

    <form id="searchbarid" name="Search"  action="<?php echo BASE; ?>projetos/mostrar" method="get">
        <div class="form-group">


          <div class="col-sm-12">
            <h3>Projetos por Instituição.</h3>
            <legend></legend>
          </div>
          
            <div class="col-sm-8">
            <label for="nome" class="col-sm-0 control-label">Pesquisar:</label>
                <select class="form-control" name = "name_institution" id="name_institution">
                    <?php 
                        foreach ($view_institutions as $institution) :
                          if (!$institution->situation) : ?>
                    ?>
                       <option>
                           CNPJ>> <?php echo $institution->cnpj; ?> >>
                          <?php echo $institution->name_institution; ?>                        
                        </option>
                    <?php 
                    endif;
                    endforeach;
                  ?>
                </select><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-0 col-sm-10">
                <input type='submit' name="Submit" value="Pesquisar" class="btn btn-success"/>
            </div>
        </div> 

    </form>

    <form action ="<?php echo BASE; ?>projetos/atualizar" enctype="multipart/form-data" class="form-horizontal" method = "post">

       <div class="form-group">
        <label for="nome" class="col-sm-3 control-label">Projetos encontradas:</label>
        <div class="col-sm-8">
          <select required class="form-control" name = "name_institution" id="name_institution">
                 <?php
                if (!empty($view_projetos)) : 
                foreach ($view_projetos as $pro) :
              ?>           
                <option>
                    ID:>> <?php echo $pro->id; ?> >>
                    <?php echo $pro->titulo; ?>                     
                </option>
              <?php 
                 endforeach;
                 endif;
              ?>
            </select>
          </div>
      </div>  

      <div class="form-group">
        <label for="imagem" class="col-sm-3 control-label">Titulo:</label>
        <div class="col-sm-8">
           <input required type="text" name="titulo" class="form-control" id="titulo" placeholder="">
        </div>
    </div>

    <div class="form-group">
        <label for="objetivo" class="col-sm-3 control-label">Objetivo geral:</label>
        <div class="col-sm-8">
           <input required type="text" name="objetivo" class="form-control" id="objetivo" placeholder="">
        </div>
    </div>

    <div class="form-group">
            <label for="exampleTextarea" class="col-sm-3 control-label">Houve dificuldades na execução do projeto? Quais? </label>
          <div class="col-sm-8">
          
          <textarea class="form-control" name= "questao" id="questao" rows="3"></textarea>   
        </div>
    </div>

      <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label">Projeto</label>
          <input required type="file" name="arquivo" id="arquivo" >
        </div>
     
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <input type="submit" class="btn btn-success">
                <input type="reset" class="btn btn-success" value="Limpar">
                <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
            </div>
        </div>
    </form>
</div>