<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">

<?php echo (isset($this->alert) ? $this->alert:''); ?>

    <form action ="<?php echo BASE; ?>juridico/registrar" enctype="multipart/form-data" class="form-horizontal" method = "post">  

     <h4 class="alert alert-info">
        Nesta tela é possível criar ou atualizar relatório de Jurídico. <br>
        Basta pesquisar o nome da instituição na lista abaixo, preencher o formulário e clicar em Enviar. <br>
        Verifique a situação da instituição na aba Relatórios. <br>
        Apenas instituições com situação em aberto são listadas abaixo.

    </h4>
    
    <h3>Selecione uma instituição</h3>
    <legend></legend> 

        <div class="form-group">
          <label for="nome" class="col-sm-3 control-label">Nome da Instituição:</label>
          <div class="col-sm-8">
              <select class="form-control" name = "name_institution" id="name_institution">
                  <?php 
                    foreach ($view_institutions as $institution) :
                      if (!$institution->situation) : ?>
                  ?>
                    <option>
                       CNPJ>> <?php echo $institution->cnpj; ?> >>
                      <?php echo $institution->name_institution; ?>                        
                    </option>
                  <?php 
                     endif;
                    endforeach;
                  ?>    
              </select>
           </div>
        </div>

        <h3>Regularização jurídica da instituiçõe</h3>
        <legend></legend>

        <div class="form-group">
            <label for="imagem" class="col-sm-3 control-label">Ata da Diretoria</label>
            <input required type="file" name="ata" id="ata" >
        </div>

        <div class="form-group">
            <label for="imagem" class="col-sm-3 control-label">Estatuto</label>
            <input required type="file" name="estatuto"  id="estatuto" >
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <input type="submit" class="btn btn-success">
                <input type="reset" class="btn btn-success" value="Limpar">
                <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
            </div>
        </div>
    </form> 
</div>
