<div class="panel-body ">
    <?php echo (isset($this->alert) ? $this->alert:''); ?>
    <form action ="<?php echo BASE; ?>login/logar/" class="form-horizontal" method = "post">
       
        <div class="form-group">
            <label for="username" class="col-sm-3 control-label">Nome usuário:</label>
            <div class="col-sm-8">
                <input type="text" name="username" class="form-control" id="username" placeholder="Nome de usuário">
            </div>
        </div>

        <div class="form-group">
            <label for="inputPassword3" class="col-sm-3 control-label">Senha</label>
                <div class="col-sm-8">
                    <input type="password" name="password" class="form-control" id="password" placeholder="Senha">
                </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-success">Entrar</button>
                <a href="<?php echo BASE; ?>cadastro/" style="color:  #0071BF">Cadastre-se aqui</a>
            </div>
        </div>
    </form>
</div>
