<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">
  <?php echo (isset($this->alert) ? $this->alert:''); ?>

  <form action ="<?php echo BASE; ?>aplicacao/registrar/" enctype="multipart/form-data" class="form-horizontal" method = "post">
    
    <h3>Relatório de Diagnóstico</h3>
    <legend></legend>
    <h4 class="alert alert-info">
        Nesta tela é possível criar ou atualizar relatório de monitoramento. <br>
        Basta pesquisar o nome da instituição na lista abaixo, preencher o formulário e clicar em Enviar. <br>
        Verifique a situação da instituição na aba Relatórios. <br>
        Apenas instituições com situação em aberto são listadas abaixo.

    </h4>
    <div class="form-group">

      <label for="nome" class="col-sm-3 control-label">Nome da Instituição:</label>
      <div class="col-sm-8">

          <select class="form-control" name = "nome_instituicao" id="nome_instituicao" >
            <option>Selecione uma Instituição Cadastrada</option>
              <?php                
                foreach ($view_institutions as $institution) :
                  if (!$institution->situation) : ?>                    
                    <option>
                       CNPJ>> <?php echo $institution->cnpj; ?> >>
                      <?php echo $institution->name_institution; ?>                        
                    </option>
                <?php endif;
                endforeach; ?>    
          </select>
       </div>
    </div>
        
    <h3>Aplicação a ser Validada</h3>
    <legend></legend>
    <h4 class="alert alert-info">
        Selecione uma opção na lista do campo 1 ou digite uma aplicação no campo 2. Será salvo a informação digitada no campo 2. Para salvar a informação pré-definida na lista do campo 1 basta deixar o campo 2 em branco.  
    </h4>
      <div class="form-group">
        <label for="aplicacao" class="col-sm-3 control-label">Aplicação (campo 1)</label>
        <div class="col-sm-8">
          <select class="form-control" name = "aplicacao1" id="aplicacao1">
             
              <option>Reforma da Unidade</option>
              <option>Reconstrução de Caixa D’Água</option>
              <option>Materiais para reforma por mutirão</option>
              <option>Aquisição de terreno para ampliação</option>
              <option>Reforma do telhado</option>
              <option>Reforma da unidade e melhorias no atendimento</option>
              <option>Construção de salas de aula de informática para crianças da comunidade</option>
              <option>Reforma da cozinha industrial e outras instalações</option>
 
          </select>       
        </div>
      </div>

      <div class="form-group">
        <label for="aplicacao" class="col-sm-3 control-label">Aplicação (campo 2)</label>
        <div class="col-sm-8">
           <input type="text" name="aplicacao2" class="form-control" id="aplicacao2" placeholder="">
        </div>
      </div>

       <div class="form-group">
          <label for="rel_diag" class="col-sm-3 control-label">Relatório de Diagnóstico</label>
          <input type="file" name="rel_diag" id="rel_diag" >
        </div>

      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Validar</label>
            <input type="radio" name="apl_validacao" id="apl_validacao" value="1" checked >Sim
            <input type="radio" name="apl_validacao" id="apl_validacao" value="0">Não 
      </div>

      <h3>Apresentação do projeto 1</h3>
      <legend></legend>
      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Data</label>
          <div class="col-sm-8">
              <input type="date" name="data_apr_1" class="form-control" id="data_apr_1">
          </div>
      </div>

      <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label">Ata</label>
          <input type="file" name="ata_apr_1" id="ata_apr_1" >
        </div>

         <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label"> Evidência</label>
          <input type="file" name="img_apr_1" id="img_apr_1" >
        </div>

      <h3>Apresentação do projeto 2</h3>
       <legend></legend>
      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Data</label>
          <div class="col-sm-8">
              <input type="date" name="data_apr_2" class="form-control" id="data_apr_2">
          </div>
      </div>

       <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label">Ata</label>
          <input type="file" name="ata_apr_2" id="apl_ata_apr_2" >
        </div>

        <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label"> Evidência</label>
          <input type="file" name="img_apr_2" id="img_apr_2" >
        </div>

        <h3>Apresentação do projeto 3</h3>
       <legend></legend>
      <div class="form-group">
          <label for="imagem" class="col-sm-3 control-label">Data</label>
          <div class="col-sm-8">
              <input type="date" name="data_apr_3" class="form-control" id="data_apr_3">
          </div>
      </div>

        <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label">Ata</label>
          <input type="file" name="ata_apr_3" id="ata_apr_3" >
        </div>    

        <div class="form-group">
          <label for="apl_img" class="col-sm-3 control-label"> Evidência</label>
          <input type="file" name="img_apr_3" id="img_apr_3" >
        </div>
  
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
          <input type="submit" class="btn btn-success">
          <input type="reset" class="btn btn-success" value="Limpar">
          <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
        </div>
      </div>
  </form>               
</div>
 