<div class="panel-heading">
    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
</div>
<div class="panel-body">
    <?php echo (isset($this->alert) ? $this->alert:''); ?>
    <div class="col-sm-12">
      <h3>Cronograma Físico-Financeiro</h3>
      <legend></legend>

        <h4 class="alert alert-info">
            Nesta tela é possível criar e/ou atualizar relatório Financeiro. <br>
            Para criar novo relatório basta clicar em Novo.<br>
            Para atualizar um relatório:<br>
            1. Selecionar o nome da instituição, <br>
            2. Clicar em Pesquisar, <br> 
            3. Selecionar qual relatório deseja atualizar, <br>
            4. Preencher o formulário e <br>
            5. Clicar em Enviar. <br>
            Verifique a situação da instituição na aba Relatórios. <br>
            Apenas instituições com situação em aberto são listadas abaixo.
        </h4>
    </div> 

        <div class="form-group">
            <div  class="col-sm-offset-0 col-sm-10">
                <a href="<?php echo BASE . 'financeiro/cadastrar'; ?>" class="btn btn-success" > Novo   </a>  
            </div>
        </div> 

    <form id="searchbarid" name="Search"  action="<?php echo BASE; ?>financeiro/mostrar" method="get">
        <div class="form-group">

          <div class="col-sm-12">
            <h3>Atualizar cronograma Físico-Financeiro</h3>
            <legend></legend>
          </div> 
            
            <div class="col-sm-8">
            <label for="nome" class="col-sm-0 control-label">Pesquisar:</label>
                <select class="form-control" name = "name_institution" id="name_institution">
                    <?php 
                        foreach ($view_institutions as $institution) :
                          if (!$institution->situation) : ?>
                    ?>
                       <option>
                           CNPJ>> <?php echo $institution->cnpj; ?> >>
                          <?php echo $institution->name_institution; ?>                        
                        </option>
                    <?php 
                    endif;
                    endforeach;
                  ?>
                </select><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-0 col-sm-10">
                <input type='submit' name="Submit" value="Pesquisar" class="btn btn-success"/>
            </div>
        </div> 

    </form>

    <form action ="<?php echo BASE; ?>financeiro/atualizar" enctype="multipart/form-data" class="form-horizontal" method = "post">
    
    <div class="form-group">
      <label for="nome" class="col-sm-3 control-label">Relatórios financeiros encontrados:</label>
      <div class="col-sm-8">
        <select class="form-control" name = "name_institution" id="name_institution">
              <?php
                if (!empty($view_financial)) : 
                foreach ($view_financial as $fin) :
              ?>           
                <option>
                    ID:>> <?php echo $fin->id; ?> >>
                    <?php echo $fin->acao; ?>  >>
                    <?php echo date( 'd/m/Y', strtotime($fin->desembolso_data)); ?>            
                </option>
              <?php 
                 endforeach;
                 endif;
              ?>
          </select>
        </div>
    </div>      

    <div class="form-group">
        <label for="imagem" class="col-sm-3 control-label">Ação:</label>
        <div class="col-sm-8">
           <input required type="text" name="acao" class="form-control" id="acao" placeholder="">
        </div>
    </div>

    <div class="form-group">
        <label for="imagem" class="col-sm-3 control-label">Valor:</label>
        <div class="col-sm-8">
           <input type="text" name="desembolso_valor" class="form-control" id="desembolso_valor" placeholder="R$">
        </div>
    </div>

    <div class="form-group">
        <label for="imagem" class="col-sm-3 control-label">Data de Desembolso:</label>
        <div class="col-sm-8">
           <input required type="date" name="desembolso_data" class="form-control" id="desembolso_data">
        </div>
    </div>
    <div class="form-group">
        <label for="imagem" class="col-sm-3 control-label">Relatório Financeiro:</label>
        <input required type="file" name="rel_financeiro" id="rel_financeiro" >
    </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
            <input type="submit" class="btn btn-success">
            <input type="reset" class="btn btn-success" value="Limpar">
            <a href="<?php echo BASE; ?>home/" style="color:  #0071BF">Retornar para Home</a>
        </div>
      </div>
    </form>
</div>